services:
    app:
        build:
            context: ./backend
        container_name: app
        volumes:
            - ./backend:/var/www/html
            - ./backend/storage:/var/www/html/storage
        working_dir: /var/www/html
        depends_on:
            - db
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
        networks:
            - app-network
        command: bash -c "php artisan serve --host=0.0.0.0 --port=8000"
        ports:
            - "8000:8000"

    db:
        image: mysql:8.0
        container_name: db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: laravel_pass
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - app-network

    frontend:
        image: node:18
        container_name: frontend
        working_dir: /app
        volumes:
            - ./frontend:/app
        ports:
            - "3000:3000"
        command: bash -c "yarn install && yarn start"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    db-data: